# Generated by Django 3.2.4 on 2021-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('V', 'Benzyna'), ('R', 'LPG'), ('A', 'Diesel')], max_length=64),
        ),
    ]
