# Generated by Django 3.2.4 on 2021-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0002_alter_pojazdy_rodzaj_paliwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('A', 'Osobowy'), ('N', 'Ciezarowy'), ('N', 'Motocykl')], max_length=24),
        ),
    ]
