# Generated by Django 3.2.4 on 2021-06-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0004_auto_20210630_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('R', 'LPG'), ('V', 'Benzyna'), ('A', 'Diesel')], max_length=64),
        ),
    ]
