# Generated by Django 3.2.4 on 2021-06-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0005_alter_pojazdy_rodzaj_paliwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('N', 'Ciezarowy'), ('A', 'Osobowy'), ('N', 'Motocykl')], max_length=24),
        ),
    ]
