# Generated by Django 3.2.4 on 2021-07-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0009_auto_20210702_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('N', 'Ciezarowy'), ('N', 'Motocykl'), ('A', 'Osobowy')], max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('R', 'LPG'), ('A', 'Diesel'), ('V', 'Benzyna')], max_length=64),
        ),
    ]
