# Generated by Django 3.2.4 on 2021-07-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0012_auto_20210703_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('A', 'Osobowy'), ('N', 'Motocykl'), ('N', 'Ciezarowy')], max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('A', 'Diesel'), ('R', 'LPG'), ('V', 'Benzyna')], max_length=64),
        ),
    ]
