# Generated by Django 3.2.4 on 2021-07-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0013_auto_20210703_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('N', 'Ciezarowy'), ('A', 'Osobowy'), ('N', 'Motocykl')], max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('R', 'LPG'), ('V', 'Benzyna'), ('A', 'Diesel')], max_length=64),
        ),
    ]
