# Generated by Django 3.2.4 on 2021-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0016_auto_20210703_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('N', 'Motocykl'), ('A', 'Osobowy'), ('N', 'Ciezarowy')], max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('A', 'Diesel'), ('V', 'Benzyna'), ('R', 'LPG')], max_length=64),
        ),
    ]
