# Generated by Django 3.2.4 on 2021-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0017_auto_20210704_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('A', 'Osobowy'), ('N', 'Ciezarowy'), ('N', 'Motocykl')], max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('V', 'Benzyna'), ('R', 'LPG'), ('A', 'Diesel')], max_length=64),
        ),
    ]
