# Generated by Django 3.2.4 on 2021-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0018_auto_20210704_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('N', 'Ciezarowy'), ('A', 'Osobowy'), ('N', 'Motocykl')], max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('A', 'Diesel'), ('R', 'LPG'), ('V', 'Benzyna')], max_length=64),
        ),
    ]
