# Generated by Django 3.2.4 on 2021-07-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0020_auto_20210705_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='PojazdyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytul', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='pojazdy',
            name='Data_dodania',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Osobowy', 'Osobowy'), ('Ciezarowy', 'Ciezarowy'), ('Motocykl', 'Motocykl')], max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Benzyna', 'Benzyna')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia_samochodow'),
        ),
    ]
