# Generated by Django 3.2.4 on 2021-07-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0021_auto_20210707_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazdy',
            name='Kategoria',
        ),
        migrations.AddField(
            model_name='pojazdytest',
            name='Kategoria',
            field=models.CharField(choices=[('Motocykl', 'Motocykl'), ('Ciezarowy', 'Ciezarowy'), ('Osobowy', 'Osobowy')], default='', max_length=24),
        ),
    ]
