# Generated by Django 3.2.4 on 2021-07-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0023_auto_20210707_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Ciezarowy', 'Ciezarowy'), ('Osobowy', 'Osobowy'), ('Motocykl', 'Motocykl')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='pojazdy',
            name='Marka',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pojazdy',
            name='Model',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pojazdy',
            name='Opis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pojazdytest',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('LPG', 'LPG'), ('Diesel', 'Diesel')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('LPG', 'LPG'), ('Diesel', 'Diesel')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pojazdytest',
            name='Kategoria',
            field=models.CharField(choices=[('Ciezarowy', 'Ciezarowy'), ('Osobowy', 'Osobowy'), ('Motocykl', 'Motocykl')], default='', max_length=24),
        ),
    ]
