# Generated by Django 3.2.4 on 2021-07-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0024_auto_20210707_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazdytest',
            name='Moc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pojazdytest',
            name='Pojemnosc_skokowa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pojazdytest',
            name='Przebieg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pojazdytest',
            name='Rok_produkcji',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Benzyna', 'Benzyna'), ('Diesel', 'Diesel')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pojazdytest',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Benzyna', 'Benzyna'), ('Diesel', 'Diesel')], default='', max_length=64),
        ),
    ]
