# Generated by Django 3.2.4 on 2021-07-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0025_auto_20210707_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazdytest',
            name='Data_dodania',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pojazdytest',
            name='Data_publikacji',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Ciezarowy', 'Ciezarowy'), ('Motocykl', 'Motocykl'), ('Osobowy', 'Osobowy')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Diesel', 'Diesel'), ('Benzyna', 'Benzyna')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pojazdytest',
            name='Kategoria',
            field=models.CharField(choices=[('Ciezarowy', 'Ciezarowy'), ('Motocykl', 'Motocykl'), ('Osobowy', 'Osobowy')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdytest',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Diesel', 'Diesel'), ('Benzyna', 'Benzyna')], default='', max_length=64),
        ),
    ]
