# Generated by Django 3.2.4 on 2021-07-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0026_auto_20210707_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazdytest',
            name='Zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia_samochodow'),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Motocykl', 'Motocykl'), ('Ciezarowy', 'Ciezarowy'), ('Osobowy', 'Osobowy')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdytest',
            name='Data_dodania',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pojazdytest',
            name='Kategoria',
            field=models.CharField(choices=[('Motocykl', 'Motocykl'), ('Ciezarowy', 'Ciezarowy'), ('Osobowy', 'Osobowy')], default='', max_length=24),
        ),
    ]
