# Generated by Django 3.2.4 on 2021-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0029_auto_20210708_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazdy',
            name='Uzytkownik',
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Motocykl', 'Motocykl'), ('Osobowy', 'Osobowy'), ('Ciezarowy', 'Ciezarowy')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Benzyna', 'Benzyna'), ('LPG', 'LPG')], default='', max_length=64),
        ),
    ]
