# Generated by Django 3.2.4 on 2021-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0035_auto_20210708_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazdy',
            name='Uzytkownik',
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Osobowy', 'Osobowy'), ('Motocykl', 'Motocykl'), ('Ciezarowy', 'Ciezarowy')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('LPG', 'LPG'), ('Diesel', 'Diesel')], default='', max_length=64),
        ),
    ]
