# Generated by Django 3.2.4 on 2021-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0037_auto_20210708_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Diesel', 'Diesel'), ('Benzyna', 'Benzyna')], default='', max_length=64),
        ),
    ]
