# Generated by Django 3.2.4 on 2021-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0039_auto_20210708_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Ciezarowy', 'Ciezarowy'), ('Osobowy', 'Osobowy'), ('Motocykl', 'Motocykl')], default='', max_length=24),
        ),
    ]
