# Generated by Django 3.2.4 on 2021-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0040_alter_pojazdy_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Osobowy', 'Osobowy'), ('Ciezarowy', 'Ciezarowy'), ('Motocykl', 'Motocykl')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Diesel', 'Diesel'), ('Benzyna', 'Benzyna')], default='', max_length=64),
        ),
    ]
