# Generated by Django 3.2.4 on 2021-07-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0041_auto_20210708_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Osobowy', 'Osobowy'), ('Motocykl', 'Motocykl'), ('Ciezarowy', 'Ciezarowy')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Benzyna', 'Benzyna')], default='', max_length=64),
        ),
    ]
