# Generated by Django 3.2.4 on 2021-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0044_auto_20210712_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazdy',
            name='user',
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Ciezarowy', 'Ciezarowy'), ('Osobowy', 'Osobowy'), ('Motocykl', 'Motocykl')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Benzyna', 'Benzyna')], default='', max_length=64),
        ),
    ]
