# Generated by Django 3.2.4 on 2021-07-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0048_auto_20210712_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Motocykl', 'Motocykl'), ('Osobowy', 'Osobowy'), ('Ciezarowy', 'Ciezarowy')], default='', max_length=24),
        ),
    ]
