# Generated by Django 3.2.4 on 2021-07-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0050_auto_20210712_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojazdy',
            name='user',
        ),
        migrations.AddField(
            model_name='pojazdy',
            name='Uzytkownik',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Kategoria',
            field=models.CharField(choices=[('Ciezarowy', 'Ciezarowy'), ('Motocykl', 'Motocykl'), ('Osobowy', 'Osobowy')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('LPG', 'LPG'), ('Benzyna', 'Benzyna'), ('Diesel', 'Diesel')], default='', max_length=64),
        ),
    ]
