# Generated by Django 3.2.4 on 2021-07-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0051_auto_20210712_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazdy',
            name='Rodzaj_paliwa',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Benzyna', 'Benzyna')], default='', max_length=64),
        ),
    ]
